server:
  port: 1234
  servlet:
    context-path: /

spring:
  redis:
    host: 192.168.50.11
    port: 6379
    database: 3
  #MQTT配置信息
  mqtt:
    #MQTT服务端地址，端口默认为11883，如果有多个，用逗号隔开
    url: tcp://110.42.210.108:1883
    #用户名
    username: admin
    #密码
    password: public
    #客户端id（不能重复）
    client:
      consumer:
        id: consumer_id
      provider:
        id: provider_id
    #MQTT默认的消息推送主题，实际可在调用接口时指定
    default:
      topic: fb/up/#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.42.210.108:3306/smart-device?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Guyue123.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#by zhengkai.blog.csdn.net
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#mqtt的配置
mqtt:
  server:
    qos: 0
    url: tcp://110.42.210.108:1883
    port: 1883
    username: admin
    password: public
  client:
    consumerId: consumerCo
    publishId: publishCo
  default:
    topic: fb/#
    completionTimeout: 3000

